export const NAVIGATION = [
  { title: "대시보드", path: "/" },
  { title: "회원 관리", path: "/users?page=1&search=" },
  { title: "경기 관리", path: "/games?page=1&search=" },
  { title: "코트 관리", path: "/courts?page=1&search=" },
  { title: "팀 관리", path: "/teams?search=" },
  { title: "신고 관리", path: "/reports?page=1&search=" },
  { title: "정산 관리", path: "/settlements?page=1&search=" },
  { title: "리뷰 관리", path: "/reviews?search=" },
  { title: "문의 관리", path: "/inquiry?page=1&search=" },
  { title: "익명 문의", path: "/anonymous-inquiry?search=" },
  { title: "쿠폰 관리", path: "/coupons" },
  { title: "공지사항 관리", path: "/notifications?search=" },
  { title: "광고/팝업 관리", path: "/popups" },
];
